/*

* To change this license header, choose License Headers in Project Properties.

* To change this template file, choose Tools | Templates

* and open the template in the editor.

*/

package student;

 

import javax.swing.JOptionPane;

import javax.swing.table.TableModel;

 

import java.awt.BorderLayout;

import java.awt.EventQueue;

 

import javax.swing.JFrame;

import javax.swing.JPanel;

import javax.swing.border.EmptyBorder;

import javax.swing.JLabel;

import javax.swing.ImageIcon;

import java.awt.Font;

import java.sql.SQLException;

import java.util.logging.Level;

import java.util.logging.Logger;

import javax.swing.JTextField;

import javax.swing.JButton;

import project.MainFrame;
import java.awt.Color;

 

/**

*

* 

*/

public class StudentFrame extends JFrame {

    int faculty=0;

    ModelStudentMongo std = new ModelStudentMongo();

    private JPanel contentPane;

      

 

    /**

     * Creates new form StudentFrame

     */

    public StudentFrame(int i) {
    getContentPane().setBackground(Color.DARK_GRAY);

     

        

        

         JLabel background=new JLabel(new ImageIcon("C:\\Users\\..\\Downloads\\bc2.jpg"));

 

        getContentPane().add(background);

         initComponents();

         this.faculty=i;

         this.addRowStd();

    }

 

    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                         

    private void initComponents() {

 

        jScrollPane1 = new javax.swing.JScrollPane();

        jTable1 = new javax.swing.JTable();

        jTextField1 = new javax.swing.JTextField();

        jButton1 = new javax.swing.JButton();

        jLabel1 = new javax.swing.JLabel();

        jButton2 = new javax.swing.JButton();

 

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setBackground(new java.awt.Color(102, 255, 102));

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

 

        jTable1.setModel(new javax.swing.table.DefaultTableModel(

            new Object [][] {

 

            },

            new String [] {

                "name", "subject", "date"

            }

        ));

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {

                jTable1MouseClicked(evt);

            }

        });

        jScrollPane1.setViewportView(jTable1);

 

        jTextField1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jTextField1ActionPerformed(evt);

            }

        });

 

        jButton1.setText("search");

        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jButton1ActionPerformed(evt);

            }

        });

 

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Search");

 

        jButton2.setText("Back");

        jButton2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jButton2ActionPerformed(evt);

            }

        });

 

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(layout.createSequentialGroup()

                .addGap(0, 0, Short.MAX_VALUE)

                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addGap(290, 290, 290))

            .addGroup(layout.createSequentialGroup()

                .addGap(65, 65, 65)

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                    .addGroup(layout.createSequentialGroup()

                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))

                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()

                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addGap(96, 96, 96)))

                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()

                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addGap(57, 57, 57))

        );

        layout.setVerticalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()

                .addContainerGap(22, Short.MAX_VALUE)

                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addGap(41, 41, 41)

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(18, 18, 18)

                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addGap(48, 48, 48)

                .addComponent(jButton2)

                .addContainerGap())

        );

 

        pack();

    }// </editor-fold>                       

 

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                        

        // TODO add your handling code here:

        std.getSearch(this.jTable1,this.faculty,jTextField1.getText(),this);

    }                                       

 

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            

        // TODO add your handling code here:

    }                                          

 

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                    

        // TODO add your handling code here:

        int index = jTable1.getSelectedRow();

 

        TableModel model = jTable1.getModel();

        String name = model.getValueAt(index, 2).toString();

 

        JOptionPane.showMessageDialog(this,std.getText(name));

    }                                   

 

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        try {

            // TODO add your handling code here:

            MainFrame frame = new MainFrame();

            this.setVisible(false);

            frame.setVisible(true);

        } catch (SQLException ex) {

            Logger.getLogger(StudentFrame.class.getName()).log(Level.SEVERE, null, ex);

        }

    }                                       

 

    /**

     * @param args the command line arguments

     */

 

 

    // Variables declaration - do not modify                    

    private javax.swing.JButton jButton1;

    private javax.swing.JButton jButton2;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTable jTable1;

    private javax.swing.JTextField jTextField1;

    // End of variables declaration                  

 

    private void addRowStd() {

         std.getSis(this.jTable1,this.faculty);

    }

 

}
